### PR TITLE
Use golang 1.14 in builds

### PR DESCRIPTION
**Pull request by timvaillancourt**
This PR moves the repo to use [golang version 1.14](https://golang.org/doc/go1.14).

`go mod tidy` was ran after the change to 1.14, causing this error:
```
tim@Tims-MacBook-Pro freno % go build cmd/freno/main.go         
go: inconsistent vendoring in /Users/tim/go/src/github.com/github/freno:
	github.com/armon/go-metrics@v0.0.0-20190430140413-ec5e00d3c878: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/boltdb/bolt@v1.3.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/bradfitz/gomemcache@v0.0.0-20190913173617-a41fca850d0b: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-sql-driver/mysql@v1.5.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/hashicorp/go-msgpack@v0.5.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/julienschmidt/httprouter@v1.3.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/outbrain/golib@v0.0.0-20180830062331-ab954725f502: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/patrickmn/go-cache@v2.1.0+incompatible: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/rcrowley/go-metrics@v0.0.0-20190826022208-cac0b30c2563: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/sys@v0.0.0-20190602015325-4c4f7f33c9ed: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	vitess.io/vitess@v2.1.1+incompatible: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
```

 So I also ran `go mod vendor`, which caused the changes to the `vendor/` dir

This `go mod vendor` error is new in 1.14, explained below:
> Vendoring
>
> When the main module contains a top-level vendor directory and its go.mod file specifies go 1.14 or higher, the go command now defaults to -mod=vendor for operations that accept that flag. A new value for that flag, -mod=mod, causes the go command to instead load modules from the module cache (as when no vendor directory is present).
>
> When -mod=vendor is set (explicitly or by default), the go command now verifies that the main module's vendor/modules.txt file is consistent with its go.mod file.

### CODE REVIEW

**Comment by timvaillancourt** [comment]
> This change looks like it includes a change to the protobuf library. Was this intentional?

@davecheney yes and no, `go mod tidy` is making that change automatically

**Comment by davecheney** [comment]
What happens if you run go mod tidy without touching the go version? Can you do that as a separate step?

**Comment by timvaillancourt** [comment]
@davecheney running `go mod tidy` on `master` causes no changes but maybe I'm not following

`go mod tidy` must be ran after swapping to the 1.14 due to the error in my first reply. This error is new in 1.14

**Comment by davecheney** [comment]
Thanks for confirming, the operation of `go mod` is opaque and confusing.

Re: staying on older version of protobuf; none that I know of other than it will cause problems in the future when you have to update to get a bug fix and the jump is larger.

**Comment by timvaillancourt** [comment]
> Thanks for confirming, the operation of `go mod` is opaque and confusing.

Yeah it really is 😄! I'm not sure why it is so insistent on upgrading that package but I havn't seen any issues so far

> Re: staying on older version of protobuf; none that I know of other than it will cause problems in the future when you have to update to get a bug fix and the jump is larger.

That's a good point that I'll keep an 👁️ out for

**Pull request merged**
