### PR TITLE
Vitess: ignore unhealthy replicas with realtime stats

### PR DESCRIPTION
**Pull request by timvaillancourt**
This PR causes Freno to ignore Vitess tablets that return unhealthy realtime tablet stats, similar to [the way `vtgate` filters replicas for serving traffic](https://github.com/vitessio/vitess/blob/master/go/vt/discovery/replicationlag.go#L113-L119), minus replication and minimum node count checks

The added logic in this PR relies on realtime stats _(an optional feature)_ and new `vtctld` API fields added to Vitess 8.0.0, but if these fields are not found the old logic is used, making this change backwards-compatible. If no stats are found tablets are assumed to be healthy like we do today

Example API of the new `/keyspace/<ks>/tablets/` API response with additional realtime stats:
```
$ curl -s https://<VTCTLD HOSTNAME>/api/keyspace/test_ks/tablets/ |jq '.[] | select( .hostname == "<REDACTED>" ).stats'
{
  "last_error": "vttablet error: replication is not running",
  "realtime": {
    "health_error": "replication is not running"
  },
  "serving": false,
  "up": true
}
```

For the most part the logic is:
1. ~~`serving` must be `true`~~ _(we need to ignore `serving`, see comments below)_
2. `last_error` must be `""` _(empty)_
3. `realtime` sub-document is not `nil`
    - I believe this check ignores tablets that haven't registered with `vtctld` yet, but it's a guess - [just copying what Vitess did](https://github.com/vitessio/vitess/blob/master/go/vt/discovery/replicationlag.go#L113-L119) so we see the same tablets as `vtgate`/clients 👍

cc @tomkrouper / @drogart / @shlomi-noach

### CODE REVIEW

**Comment by timvaillancourt** [comment]
@tomkrouper / @drogart / @shlomi-noach: should we also ignore nodes with `serving: false`? Is there ever cases where vtgates direct traffic to a tablet in `serving: false` state or Freno should wait for a tablet in `serving: false` to catch up? 

Overall the "serving" term isn't 100% clear to me 🤔

**Comment by timvaillancourt** [comment]
With some advice from PlanetScale [I believe I've matched the logic `vtgate` uses to find tablets](https://github.com/vitessio/vitess/blob/3b94d7a08473b60ac1d0974de88f022260dc0897/go/vt/vtgate/tabletgateway.go#L238), minus the logic for checking replication lag _(Freno will do this)_ and minimum tablet count 👍 

Path I followed through the code:
1. https://github.com/vitessio/vitess/blob/master/go/vt/vtgate/tabletgateway.go `*TabletGateway.withRetry(...)`
2. https://github.com/vitessio/vitess/blob/master/go/vt/discovery/healthcheck.go `*HealthCheckImpl.GetHealthyTabletStats(...)`
3. https://github.com/vitessio/vitess/blob/master/go/vt/discovery/replicationlag.go `*FilterStatsByReplicationLag(...)`

**Review by shlomi-noach — APPROVED** [review]
This looks to be right. Mind you that I'm not that familiar with realtime stats in Vitess.

**Review by drogart — APPROVED** [review]

**Comment by timvaillancourt** [comment]
> This looks to be right. Mind you that I'm not that familiar with realtime stats in Vitess.

After some testing with Vitess the logic in this PR won't work as it stands. When a node is considered "unhealthy" by Vitess, the following is returned by the `vtctld` API:
```json
$ curl -ks https://<vtctld hostname>/api/keyspace/test_ks/tablets/?cells=dc1 \
    | jq '.[] | select( .hostname == "<hostname>" ).stats'
{
  "realtime": {
    "seconds_behind_master": 30
  },
  "serving": false,
  "up": true
}
```
This response was gathered from a node that exceeds the `-discovery_high_replication_lag_minimum_serving` threshold

While Vitess won't send reads to a replica in `serving: false`, this discovery means that the logic in this PR will cause Freno to ignore lagging nodes, allowing more writes vs throttling when replication is overwhelmed - because any lagging node will become `serving: false`

This means:
1. This PR needs to consider `serving: false` **AND** `serving: true` for Freno probes
2. There will still be cases where a broken node can cause Freno to throttle _(although the replica is not `serving` in Vitess)_:
    - Replication hit an error
    - Replication was stopped

Apparently `vtctld` doesn't "notice" situations where replication is broken _(after previously being healthy)_, only the replication lag caused by the problem is reported. This means we're currently unable to differentiate a "broken" node from a "lagging" one

Having Vitess periodically update the `last_error` in Realtime stats with the health of replication threads would allow us to know when replication is broken vs overwhelmed. Currently `replication is not running` is returned on a new tablet that has never replicated, but not when a previously-health tablet hits a problem

cc @tomkrouper / @shlomi-noach for thoughts

**Comment by timvaillancourt** [comment]
Re-requesting review from @shlomi-noach, @drogart and @tomkrouper

**Review by drogart — APPROVED** [review]

**Pull request merged**
